// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cntukzijxhhoibapqwuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNudHVremlqeGhob2liYXBxd3V5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNTU4MTksImV4cCI6MjA2NjYzMTgxOX0.-svmdvpmlTq_4OLlt_AOrQ2uHa8enKofPqUFtA-Ykyg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);