// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmootzggzmcgnttreben.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtb290emdnem1jZ250dHJlYmVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMDQyMzYsImV4cCI6MjA2Njg4MDIzNn0.cpvolwXGOrVL2STd3CjPHR6x2lH1ThaoK_bBte2FfaY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});